# Generated by Django 4.2.13 on 2024-05-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency_name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=64)),
                ('logo', models.URLField(blank=True, null=True)),
                ('current_price', models.CharField(max_length=64)),
                ('hourly_change', models.CharField(max_length=64)),
                ('daily_change', models.CharField(max_length=64)),
                ('weekly_change', models.CharField(max_length=64)),
                ('market_capital', models.CharField(max_length=255)),
                ('trade_volume_usd', models.CharField(max_length=255)),
                ('trade_volume_crypto', models.CharField(max_length=255)),
                ('circulating_supply', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
